cache_directory: './tmp/cache/git'
maximum_branches_to_check: 100
email_override: 'test@email.com' #redirect all emails to this address
email_filter: [] #only email users in this list. Empty to disable filter.
repos_to_check:
  MyRepo:
    repo_name: 'Organization/repo'
    ignore_branches: [] #regex
    ignore_branches_modified_days_ago: 28
    only_branches: ['^folder/.*$', 'master'] #regex
    ignore_conflicts_in_file_paths: ['^test/fixtures/.*$', '^lib/data/generated/.*$'] #regex
    master_branch_name: 'master'
    suppress_conflicts_for_owners_of_branches: ['master', 'production']
