cache_directory: './tmp/cache/git'
maximum_branches_to_check: 0
email_override: '' #redirect all emails to this address
email_filter: [] #only email users in this list. Empty to disable filter.
bcc_emails: [] # BCC these addresses on every email sent
web_server_url: 'http://localhost:3000'
repositories_to_check_for_conflicts:
  MyRepo:
    repository_name: 'Organization/repository'
    ignore_branches: [] #regex
    ignore_branches_modified_days_ago: 28
    only_branches: ['^folder/.*$', 'master'] #regex
    ignore_conflicts_in_file_paths: ['^test/fixtures/.*$', '^lib/data/generated/.*$'] #regex
    default_branch_name: 'master'
    suppress_conflicts_for_owners_of_branches: ['master', 'production']
jira:
  site: 'https://test.atlassian.net'
  consumer_key: 'test_consumer_key'
  access_token: 'test_access_token'
  access_key: 'test_access_key'
  private_key_file: './spec/fixtures/rsakey.pem'
  ancestor_branches:
    default: 'master'
    master: 'production'
    release: 'production'
    production: 'master'
  project_keys: ['STORY', 'TECH', 'WEB', 'OPS']
  valid_statuses: ['Ready to Deploy']
  ignore_commits_with_messages: ['(^|\s)merge($|\s)']  #regex
  ignore_branches: []  #regex
  only_branches: [] #regex
